accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path("signup/", views.SignupPageView.as_view(), name='signup'),
]

books/urls.py
from django.urls import path

from books import views

app_name = 'books'
urlpatterns = [
    path('', views.BookListView.as_view(), name='books_list'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('home.urls')),
    path('books/', include('books.urls')),
    # path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

]

home/urls.py
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path("", views.HomeView.as_view(), name='home'),
    path("about/", views.AboutView.as_view(), name='about'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

books/models.py
import uuid

from django.db import models
from django.urls import reverse


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('books:book_detail', args=[str(self.pk)])

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from accounts.forms import CustomUserCreationForm


class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

books/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from books.models import Book


class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'books/book_list.html'


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'books/book_detail.html'
    slug_field = 'uuid'

home/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home/home.html'


class AboutView(TemplateView):
    template_name = 'home/about.html'

books/templates/books/book_detail.html
{% extends 'base.html' %}

{% block title %}
{{ book.title }}
{% endblock %}

{% block content %}
        <div><h2>
            <a href="">{{ book.title }}</a>
        </h2>
        <p>Author: {{ book.author }}</p>
        <p>Author: {{ book.price }}</p>
        </div>

{% endblock content %}

books/templates/books/book_list.html
{% extends 'base.html' %}

{% block title %}
Books
{% endblock %}

{% block content %}

    {% for book in books %}
        <div><h2>
{#            <a href="{% url 'books:book_detail' book.pk %}">{{ book.title }}</a>#}
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        </h2>
        </div>
        {% empty %}
        <p><a href="">Add book</a></p>
    {% endfor %}
{% endblock content %}

home/templates/home/about.html
{% extends 'base.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h2>About</h2><br><br>
    <p>Działa? Działa &#128512;</p>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}
    Homepage
{% endblock %}

{% block content %}
    <h1>Welcome to bookstore</h1>
    {% if user.is_authenticated %}
        <h2>Hi {{ user.username }}</h2>
    {% else %}
        <p>You're not logged in</p>
        <a href="{% url 'account_login' %}">Log In</a>
{#        <br><br>#}
{#        <img src="../../../static/images/yoda.jpg" style="width: 250px; height: 400px" alt="Yoda will miss you">#}
    {% endif %}
{%  endblock content%}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar:</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>

            <li class="nav-item">
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
            {% else %}
                <a class="nav-link" href="{% url 'account_login' %}">Log in</a>

             </li>
                <li class="nav-item">
                <a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
            {% endif %}
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'home:about' %}" class="nav-link">About</a>
            </li>
          </ul>
          <span class="navbar-text">
            Navbar text with an inline element
          </span>
        </div>
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <div>

    </div>


</body>
</html>